wandb_version: 1

GPU_NUM:
  desc: null
  value: 0
batch_size:
  desc: null
  value: 1
num_epochs:
  desc: null
  value: 30
lr:
  desc: null
  value: 0.0003
report_interval:
  desc: null
  value: 100
net_name:
  desc: null
  value: test
data_path_train:
  desc: null
  value: /root/Data/train
data_path_val:
  desc: null
  value: /root/Data/val
cascade:
  desc: null
  value: 12
chans:
  desc: null
  value: 18
sens_chans:
  desc: null
  value: 8
input_key:
  desc: null
  value: kspace
target_key:
  desc: null
  value: image_label
max_key:
  desc: null
  value: max
seed:
  desc: null
  value: 2023
num_workers:
  desc: null
  value: 4
loss_mask:
  desc: null
  value: false
model:
  desc: null
  value: varnet
grad_accumulation:
  desc: null
  value: 4
grad_norm:
  desc: null
  value: 100000000.0
amp:
  desc: null
  value: false
unet:
  desc: null
  value: plain
config:
  desc: null
  value: ./utils/model/config/swin_36.yaml
scheduler:
  desc: null
  value: null
step_size:
  desc: null
  value: 5
gamma:
  desc: null
  value: 0.5
loss:
  desc: null
  value: ssim
edge_weight:
  desc: null
  value: 1
aug:
  desc: null
  value: false
edge:
  desc: null
  value: false
collate:
  desc: null
  value: false
resume_from:
  desc: null
  value: null
exp_dir:
  desc: null
  value: ../result/test/checkpoints
val_dir:
  desc: null
  value: ../result/test/reconstructions_val
main_dir:
  desc: null
  value: ../result/test/train.py
val_loss_dir:
  desc: null
  value: ../result/test
_wandb:
  desc: null
  value:
    python_version: 3.8.16
    cli_version: 0.15.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1689595125.198157
    t:
      1:
      - 1
      - 41
      - 49
      - 55
      - 63
      2:
      - 1
      - 41
      - 49
      - 55
      - 63
      3:
      - 16
      - 23
      4: 3.8.16
      5: 0.15.5
      8:
      - 4
      - 5
