MODEL:
  TYPE: swin
  NAME: swin_unet_for_varnet
  DROP_PATH_RATE: 0.2
  DROP_RATE: 0.0
  PRETRAIN_CKPT: "./pretrained_ckpt/swin_tiny_patch4_window7_224.pth"
  SWIN:
    FINAL_UPSAMPLE: "expand_first"
    EMBED_DIM: 42
    DEPTHS: [ 2, 2, 2, 2 ]
    DECODER_DEPTHS: [ 2, 2, 2, 1]
    NUM_HEADS: [ 2, 4, 7, 21]
    WINDOW_SIZE: 6
    MLP_RATIO: 4
    QKV_BIAS: True
    DROP_RATE: 0.0
    ATTENTION_DROP_RATE: 0.0
    DROP_PATH_RATE: 0.2
    NORM_LAYER: "nn.LayerNorm"
    NORM_LAYER_ARGS: {}
    PATCH_NORM: True
    PATCH_SIZE: 4
    IN_CHANS: 3
    APE: False

DATA:
  IMG_SIZE: [768, 384]
  NUM_CLASSES: 3

TRAIN:
  USE_CHECKPOINT: False