MODEL:
  TYPE: swin
  NAME: swin_tiny_patch4_window7_224
  DROP_PATH_RATE: 0.2
  PRETRAIN_CKPT: "./pretrained_ckpt/swin_tiny_patch4_window7_224.pth"
  SWIN:
    FINAL_UPSAMPLE: "expand_first"
    EMBED_DIM: 96
    DEPTHS: [ 2, 2, 2, 2 ]
    DECODER_DEPTHS: [ 2, 2, 2, 1]
    NUM_HEADS: [ 3, 6, 12, 24 ]
    WINDOW_SIZE: 7
    MLP_RATIO: 4
    QKV_BIAS: True
    QKV_SCALE: None
    DROP_RATE: 0.0
    ATTENTION_DROP_RATE: 0.0
    DROP_PATH_RATE: 0.2
    NORM_LAYER: "nn.LayerNorm"
    NORM_LAYER_ARGS: {}
    PATCH_NORM: True

DATA:
  IMG_SIZE: 224

TRAIN:
  USE_CHECKPOINT: False